Atik8x8RoCC:
    agfi: agfi-0e3bc048f0c8fb8cf
    deploy_quintuplet_override: null
    custom_runtime_config: null

Atik4x4RoCC:
    agfi: agfi-062c0b9296d0ed1bc
    deploy_quintuplet_override: null
    custom_runtime_config: null
